backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images"
public_folder: "/images"

collections:
  - name: "routetest"
    label: "Label"
    files:
      - label: "Page To Edit"
        name: "editablepage"
        file: "articlelist.json"        
        fields: 
          - label: "Article Section"
            name: "article_section"
            widget: "list"
            fields:
              - {label: "Article Name", name: "title", widget: "string"}
