backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images"
public_folder: "/images/uploads"

collections:
  - name: "routetest"
    label: "Label"
    file: "index.html"
    create: false
    fields: 
      - {label: "Title", name: "title", widget: "string"}
