backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "articles"
public_folder: "/articles"

collections:
  - name: "articles"
    label: "Articles"
    files:
      - label: "American Match Safes"
        name: "american_section"
        file: "articlelist.json"        
        fields: 
          - label: "American Match Safe articles"
            name: "american"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "European Match Safes (Vestas)"
        name: "european_section"
        file: "articlelist.json"        
        fields: 
          - label: "European Match Safe articles"
            name: "european"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "Japanese Match Safes"
        name: "japanese_section"
        file: "articlelist.json"        
        fields: 
          - label: "Japanese Match Safe articles"
            name: "japanese"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "Global Match Safes"
        name: "global_section"
        file: "articlelist.json"        
        fields: 
          - label: "Global Match Safe articles"
            name: "global"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
      - label: "Match Holders"
        name: "holder_section"
        file: "articlelist.json"        
        fields: 
          - label: "Match Holder articles"
            name: "holder"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "File", name: "path", widget: "file"}
